version: '3.9'

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD="your_password"
      - POSTGRES_USER="your_user"
      - POSTGRES_DB="dogovors"